# 在最后追加以下代码

# RB mutex related configs
obj-$(CONFIG_RB_MUTEX) += codes/rb_mutex/        # Red-Black tree based mutex implementation
obj-$(CONFIG_RB_RWMUTEX) += codes/rb_rwmutex/    # Red-Black tree based read-write mutex implementation
obj-$(CONFIG_RB_RWSEM) += codes/rb_rwsem/        # Red-Black tree based read-write semaphore implementation